# -*- coding: utf-8 -*-
"""largest_streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qe8SkFrF5gBEKCX8wmfA83uN64U3xsQP
"""

import streamlit as st
import pandas as pd


def main():
  st.title('Find the Largest Number!')
  st.header('Please enter 3 numbers to find the largest among them!!')
  num1 = st.number_input("Enter first number")
  num2= st.number_input("Enter second number")
  num3= st.number_input("Enter third number")
  
  if st.button('Find Largest'):
    if (num1 >= num2) and (num1 >= num3):
      largest = num1
    elif (num2 >= num1) and (num2 >= num3):
      largest = num2
    else:
      largest = num3
        
    st.write("The largest number among the three is : ",largest)



